# Use an official Node.js runtime as a parent image
FROM node:21.7.3-alpine3.20

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install
RUN npm install pm2 -g
# RUN npm install -g typescript
# Copy the rest of the application code to the working directory
COPY . .

# Build the TypeScript code
RUN npx prisma generate
RUN npm run build
# RUN tsc
# Expose the port your app runs on
EXPOSE 5000

# Define the command to start your application
CMD ["pm2-runtime", "start", "dist/logServer/app.js"]
